### ISSUE TITLE
WTF Crash

### ISSUE THREAD

**Issue by Pauloo27** [Craftzao/dlog#2]
Log:
```/files/Applications/Installed/dlog/app.js:31
   if(config.ignoreServerID.lenght > 2 || (msg.guild.id === config.ignoreServerID)) return;
                                                    ^

TypeError: Cannot read property 'id' of null
    at Client.client.on (/files/Applications/Installed/dlog/app.js:31:53)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (/files/Applications/Installed/dlog/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/files/Applications/Installed/dlog/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/files/Applications/Installed/dlog/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/files/Applications/Installed/dlog/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
    at WebSocket.onMessage (/files/Applications/Installed/dlog/node_modules/ws/lib/EventTarget.js:99:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
```
Config: 
```{
    "login": "(removed)",
    "ignorarUsuarioID": "",
    "ignoreServerID": "",
    "ignoreChannelID": "",
    "whiteServerID": "",
    "linguagem": "pt"
}
```

**Comment by Craftzao** [comment]
Olá, obrigado por reportar o bug, já vamos resolver
